version: 2

sources:
  - name: skusense_silver      # logical name inside dbt
    database: SKUSENSE     # your Snowflake DB
    schema: ANALYTICS             # your Snowflake SCHEMA
    tables:
      - name: INVENTORY_SILVER_VW # your external table name
        description: "Clean Silver layer inventory view from the ICEBERG-backed external table"
        columns:
          - name: product_id
            description: "Product SKU identifier."
            tests:
              - not_null
          - name: warehouse_id
            description: "Warehouse identifier."
            tests:
              - not_null
          - name: load_dt
            description: "Data load date."
            tests:
              - not_null
          - name: qty_on_hand
            descripttion: "Current inventory level"
          - name: avg_daily_usage
            description: "Average daily usage of the product."
          - name: reorder_flag
            description: "Flag indicating if the product needs to be reordered."
          - name: stock_status
            description: "Status of the stock (e.g., in stock, out of stock)."
            
          # add more important columns with tests as you go
